// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: proto/p2p.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Emails         []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"` // support multi recipient
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`   // legacy support
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Company        string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Role           string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	IsViewable     bool                   `protobuf:"varint,6,opt,name=is_viewable,json=isViewable,proto3" json:"is_viewable,omitempty"`
	Note           string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	EncryptedNote  string                 `protobuf:"bytes,8,opt,name=encrypted_note,json=encryptedNote,proto3" json:"encrypted_note,omitempty"`
	EncryptedNotes map[string]string      `protobuf:"bytes,9,rep,name=encrypted_notes,json=encryptedNotes,proto3" json:"encrypted_notes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Addresses      []string               `protobuf:"bytes,10,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Address        string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	EvidenceHash   string                 `protobuf:"bytes,12,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	EvidencePath   string                 `protobuf:"bytes,13,opt,name=evidence_path,json=evidencePath,proto3" json:"evidence_path,omitempty"`
	IsCompleted    bool                   `protobuf:"varint,14,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	CompletedAt    int64                  `protobuf:"varint,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *Checkpoint) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Checkpoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Checkpoint) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Checkpoint) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Checkpoint) GetIsViewable() bool {
	if x != nil {
		return x.IsViewable
	}
	return false
}

func (x *Checkpoint) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Checkpoint) GetEncryptedNote() string {
	if x != nil {
		return x.EncryptedNote
	}
	return ""
}

func (x *Checkpoint) GetEncryptedNotes() map[string]string {
	if x != nil {
		return x.EncryptedNotes
	}
	return nil
}

func (x *Checkpoint) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Checkpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Checkpoint) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *Checkpoint) GetEvidencePath() string {
	if x != nil {
		return x.EvidencePath
	}
	return ""
}

func (x *Checkpoint) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *Checkpoint) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type Tracker struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Privacy        string                 `protobuf:"bytes,3,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Creator        string                 `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatorAddr    string                 `protobuf:"bytes,5,opt,name=creator_addr,json=creatorAddr,proto3" json:"creator_addr,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Checkpoints    []*Checkpoint          `protobuf:"bytes,7,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	TargetEnd      string                 `protobuf:"bytes,8,opt,name=target_end,json=targetEnd,proto3" json:"target_end,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	EncryptedNotes map[string]string      `protobuf:"bytes,10,rep,name=encrypted_notes,json=encryptedNotes,proto3" json:"encrypted_notes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tracker) Reset() {
	*x = Tracker{}
	mi := &file_proto_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracker) ProtoMessage() {}

func (x *Tracker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracker.ProtoReflect.Descriptor instead.
func (*Tracker) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *Tracker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tracker) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tracker) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Tracker) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Tracker) GetCreatorAddr() string {
	if x != nil {
		return x.CreatorAddr
	}
	return ""
}

func (x *Tracker) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tracker) GetCheckpoints() []*Checkpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *Tracker) GetTargetEnd() string {
	if x != nil {
		return x.TargetEnd
	}
	return ""
}

func (x *Tracker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tracker) GetEncryptedNotes() map[string]string {
	if x != nil {
		return x.EncryptedNotes
	}
	return nil
}

type TrackerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trackers      []*Tracker             `protobuf:"bytes,1,rep,name=trackers,proto3" json:"trackers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackerList) Reset() {
	*x = TrackerList{}
	mi := &file_proto_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerList) ProtoMessage() {}

func (x *TrackerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerList.ProtoReflect.Descriptor instead.
func (*TrackerList) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *TrackerList) GetTrackers() []*Tracker {
	if x != nil {
		return x.Trackers
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{3}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_p2p_proto protoreflect.FileDescriptor

const file_proto_p2p_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/p2p.proto\x12\x05proto\"\xb3\x04\n" +
	"\n" +
	"Checkpoint\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1f\n" +
	"\vis_viewable\x18\x06 \x01(\bR\n" +
	"isViewable\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x12%\n" +
	"\x0eencrypted_note\x18\b \x01(\tR\rencryptedNote\x12N\n" +
	"\x0fencrypted_notes\x18\t \x03(\v2%.proto.Checkpoint.EncryptedNotesEntryR\x0eencryptedNotes\x12\x1c\n" +
	"\taddresses\x18\n" +
	" \x03(\tR\taddresses\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12#\n" +
	"\revidence_hash\x18\f \x01(\tR\fevidenceHash\x12#\n" +
	"\revidence_path\x18\r \x01(\tR\fevidencePath\x12!\n" +
	"\fis_completed\x18\x0e \x01(\bR\visCompleted\x12!\n" +
	"\fcompleted_at\x18\x0f \x01(\x03R\vcompletedAt\x1aA\n" +
	"\x13EncryptedNotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x03\n" +
	"\aTracker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aprivacy\x18\x03 \x01(\tR\aprivacy\x12\x18\n" +
	"\acreator\x18\x04 \x01(\tR\acreator\x12!\n" +
	"\fcreator_addr\x18\x05 \x01(\tR\vcreatorAddr\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x123\n" +
	"\vcheckpoints\x18\a \x03(\v2\x11.proto.CheckpointR\vcheckpoints\x12\x1d\n" +
	"\n" +
	"target_end\x18\b \x01(\tR\ttargetEnd\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12K\n" +
	"\x0fencrypted_notes\x18\n" +
	" \x03(\v2\".proto.Tracker.EncryptedNotesEntryR\x0eencryptedNotes\x1aA\n" +
	"\x13EncryptedNotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\vTrackerList\x12*\n" +
	"\btrackers\x18\x01 \x03(\v2\x0e.proto.TrackerR\btrackers\"\a\n" +
	"\x05Empty\" \n" +
	"\x04Pong\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbe\x01\n" +
	"\n" +
	"P2PService\x12+\n" +
	"\vSyncTracker\x12\x0e.proto.Tracker\x1a\f.proto.Empty\x12/\n" +
	"\vSyncMempool\x12\x12.proto.TrackerList\x1a\f.proto.Empty\x12!\n" +
	"\x04Ping\x12\f.proto.Empty\x1a\v.proto.Pong\x12/\n" +
	"\vGetTrackers\x12\f.proto.Empty\x1a\x12.proto.TrackerListB\x19Z\x17doc-tracker/proto;protob\x06proto3"

var (
	file_proto_p2p_proto_rawDescOnce sync.Once
	file_proto_p2p_proto_rawDescData []byte
)

func file_proto_p2p_proto_rawDescGZIP() []byte {
	file_proto_p2p_proto_rawDescOnce.Do(func() {
		file_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_p2p_proto_rawDesc), len(file_proto_p2p_proto_rawDesc)))
	})
	return file_proto_p2p_proto_rawDescData
}

var file_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_p2p_proto_goTypes = []any{
	(*Checkpoint)(nil),  // 0: proto.Checkpoint
	(*Tracker)(nil),     // 1: proto.Tracker
	(*TrackerList)(nil), // 2: proto.TrackerList
	(*Empty)(nil),       // 3: proto.Empty
	(*Pong)(nil),        // 4: proto.Pong
	nil,                 // 5: proto.Checkpoint.EncryptedNotesEntry
	nil,                 // 6: proto.Tracker.EncryptedNotesEntry
}
var file_proto_p2p_proto_depIdxs = []int32{
	5, // 0: proto.Checkpoint.encrypted_notes:type_name -> proto.Checkpoint.EncryptedNotesEntry
	0, // 1: proto.Tracker.checkpoints:type_name -> proto.Checkpoint
	6, // 2: proto.Tracker.encrypted_notes:type_name -> proto.Tracker.EncryptedNotesEntry
	1, // 3: proto.TrackerList.trackers:type_name -> proto.Tracker
	1, // 4: proto.P2PService.SyncTracker:input_type -> proto.Tracker
	2, // 5: proto.P2PService.SyncMempool:input_type -> proto.TrackerList
	3, // 6: proto.P2PService.Ping:input_type -> proto.Empty
	3, // 7: proto.P2PService.GetTrackers:input_type -> proto.Empty
	3, // 8: proto.P2PService.SyncTracker:output_type -> proto.Empty
	3, // 9: proto.P2PService.SyncMempool:output_type -> proto.Empty
	4, // 10: proto.P2PService.Ping:output_type -> proto.Pong
	2, // 11: proto.P2PService.GetTrackers:output_type -> proto.TrackerList
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_p2p_proto_init() }
func file_proto_p2p_proto_init() {
	if File_proto_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_p2p_proto_rawDesc), len(file_proto_p2p_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_p2p_proto_goTypes,
		DependencyIndexes: file_proto_p2p_proto_depIdxs,
		MessageInfos:      file_proto_p2p_proto_msgTypes,
	}.Build()
	File_proto_p2p_proto = out.File
	file_proto_p2p_proto_goTypes = nil
	file_proto_p2p_proto_depIdxs = nil
}
